### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by maciejskorski** [maciejskorski/enhanced-pll-trng#12]
by @viktorfischersenior:

1) to use Figure 3 depicting the new architecture instead of the old one.

2) to modify the text in the following way:

two Spartan devices were tested, both placed on the cards version 11, cards #2 and #8 marked S6v11_2 and S6v11_8), and by configurations described in the paper (A, B, or C with one or two PLL outputs as indicated by the suffix, e.g. A_1 vs A_2). Finally, the data files represent bitstreams available at the sampler output, i.e. the D flip-flop output marked dff_out in Figure 3). The binary files have thus extension .dff and the associated metadata files have extension .log.

**Comment by DallisonQuentin** [comment]
Done in #20
