### ISSUE TITLE
Clean extra files for S6v11_8

### ISSUE THREAD

**Issue by DallisonQuentin** [maciejskorski/enhanced-pll-trng#15]
Some files remain from running statistical tests (NIST).

**Comment by DallisonQuentin** [comment]
In branch fix-issue-#15, only two files remain :
- https://github.com/maciejskorski/enhanced-pll-trng/blob/fix-issue-%2315/data/Regular/S6v11_8/B_1/acq_20230413165757_km464_kd475_dff_rng_nist_1bit.bin
- https://github.com/maciejskorski/enhanced-pll-trng/blob/fix-issue-%2315/data/Regular/S6v11_8/C_2/acq_20230413170127_km476_kd495_dff_rng_nist_1bit.bin
They need to be deleted through command line.

**Comment by maciejskorski** [comment]
Yup, with the command line we can remove by pattern `find data -name "*nist_1bit.bin" -delete`. Done in c0db05e663dbd3cab0df76ff06661660feade7bc
